### ISSUE TITLE
Ext packer doesn't handle tuples right

### ISSUE THREAD

**Issue by clayote** [aviramha/ormsgpack#213]
I'm using MessagePack to represent [networkx](https://networkx.org/) graphs, which routinely use tuples as keys in their dictionary representation; and my graphs in particular use both tuples and lists in their values, so I have to distinguish between them. So I've made an extension type, with type code 0, to represent tuples.

ormsgpack is giving different output than the reference implementation for these cases.

```python3
from functools import partial

import msgpack
import ormsgpack


def orpack_handler(obj):
    if isinstance(obj, tuple):
        return ormsgpack.Ext(0x00,
                             orpacker(list(obj)))
    raise TypeError("unpackable")


orpacker = partial(ormsgpack.packb,
                   default=orpack_handler,
                   option=ormsgpack.OPT_NON_STR_KEYS
                          | ormsgpack.OPT_PASSTHROUGH_TUPLE)


def corepack_handler(obj):
    if isinstance(obj, tuple):
        return msgpack.ExtType(0x00,
                               corepacker(list(obj)))
    raise TypeError("unpackable")


corepacker = partial(msgpack.packb, default=corepack_handler, strict_types=True)

test_data_0 = {(0, 0): True, (0, 1): False, (1, 0): True, (1, 1): False}

assert orpacker(test_data_0) == corepacker(test_data_0)  # fails

test_data_1 = {'physical': {(0, 0): {'pos': (0.5, 0.0), '_x': 0.0, '_y': 0.0, 'name': (0, 0)},
                          (0, 1): {'pos': (0.0, 0.8660254037844386), '_x': 0.0, '_y': 0.023902439024390244,
                                   'name': (0, 1)}}}

assert orpacker(test_data_1) == corepacker(test_data_1)  # fails
```

**Comment by exg** [comment]
I do not understand what the issue is. msgpack does not use `default` for tuple objects, since it does not have the equivalent of `OPT_PASSTHROUGH_TUPLE`, while ormsgpack uses `default` but not for map keys, as passthrough is inhibited for them. As a result, the serialization is the same for `test_data_0`, as the only tuple objects are map *keys*, while it is different for `test_data_1`, as it contains tuple objects as map *values*. IOW, the msgpack serializations of `test_data_0` and `test_data_1` do not contain any Ext type, while the ormsgpack serialization of `test_data_1` contains Ext types for tuple objects that are map values. In general, it is expected that the msgpack and ormsgpack serializations are different when using `OPT_PASSTHROUGH_TUPLE`, regardless of the usage of Ext types.

**Comment by clayote** [comment]
msgpack does have an equivalent of `OPT_PASSTHROUGH_TUPLE`. It's called `strict_types` and I used it in the example code.

**Comment by clayote** [comment]
Though I see I set `strict_types` incorrectly.

Well, I've fixed it and the example code errors for the right reason now.

**Comment by clayote** [comment]
Here is the relevant text from `help(msgpack.Packer)`

```
|  :param bool strict_types:
 |      If set to true, types will be checked to be exact. Derived classes
 |      from serializeable types will not be serialized and will be
 |      treated as unsupported type and forwarded to default.
 |      Additionally tuples will not be serialized as lists.
```

**Comment by clayote** [comment]
Hm, when I turn on `strict_types` the first assertion fails. I think the Ext packer might be more broken than I thought.

**Comment by exg** [comment]
This is not specific to the Ext type. As I explained above, ormsgpack inhibits passthrough for map keys and therefore does not use `default` for tuple objects that are map keys, while msgpack does with `strict_types=True`.

**Comment by clayote** [comment]
Well, all right. Would it be practical to have an option that does passthrough for map keys?
