### ISSUE TITLE
use trusted publisher

### ISSUE THREAD

**Issue by aviramha** [aviramha/ormsgpack#323]
PyPI recently added "Trusted Publisher" concept that allows us to avoid using user-specific access keys.
(I got an email notifying me a token was used instead of that so thought it'd be a good improvement)

**Comment by exg** [comment]
We already use trusted publishing since https://github.com/aviramha/ormsgpack/commit/8c90e64f8d70958736d020973b165658081f4795 :) I used a token to publish the 1.7.0 release because of an issue in twine and gh-action-pypi-publish that is now resolved (https://github.com/aviramha/ormsgpack/issues/311#issuecomment-2526296949).

**Comment by aviramha** [comment]
Whoops!
